---
nftables_forward_rules:
  - name: forward rule
    action: accept
    sources:
      - zone: lan
        subnets: true
        sets:
          - external-hosts-example
          - wan_ip
    destinations:
      - zone: wan
        sets:
          - wan_ip
      - zone: wan
        sets:
          - external-hosts-example
      - zone: lab
        subnets: true
    destination_ports:
      tcp:
        - 22
  - name: forward rule without destination ports
    action: accept
    qos:
      mark: 10
      guarantee: 10mbit
    sources:
      - zone: lan
        subnets: true
        sets:
          - external-hosts-example
          - wan_ip
    destinations:
      - zone: wan
        sets:
          - wan_ip
      - zone: wan
        sets:
          - external-hosts-example
      - zone: lab
        subnets: true
