---
- name: Converge
  hosts: all
  become: true
  vars:
    nftables_global:
      default_policy:
        input: accept
        forward: drop
        output: accept
      logging:
        enabled: true
        level: info
      rate_limit: 1000
      counter: true
    nftables_zones:
      - name: wan
        interfaces:
          - eth0
      - name: lan
        interfaces:
          - eth1
          - eth2
        subnets:
          - 10.0.0.0/24
          - 10.0.1.0/24
        allow_intrazone_traffic: true
      - name: lab
        interfaces:
          - eth3
          - eth4
        subnets:
          - 10.13.33.0/24
          - 10.14.44.0/24
        allow_intrazone_traffic: true
    nftables_sets:
      - name: any
        subnets:
          - 0.0.0.0/0
      - name: wan_ip
        subnets:
          - 10.11.0.1
      - name: lan_host
        subnets:
          - 10.0.0.2
    nftables_dnsmasq_sets:
      - name: external-hosts-example
        hosts:
          - google.dk
          - yahoo.dk
    nftables_input_rules:
      - name: allow ssh from known good
        zone: lan
        action: accept
        sources:
          sets:
            - wan_ip
          subnets: true
        destination_ports:
          tcp:
            - 22
            - 24
          udp:
            - 23
      - name: input rule without destination ports
        zone: lan
        action: accept
        sources:
          sets:
            - wan_ip
          subnets: true
    nftables_forward_rules:
      - name: forward rule
        action: accept
        sources:
          - zone: lan
            subnets: true
            sets:
              - external-hosts-example
              - wan_ip
        destinations:
          - zone: wan
            sets:
              - wan_ip
          - zone: wan
            sets:
              - external-hosts-example
          - zone: lab
            subnets: true
        destination_ports:
          tcp:
            - 22
      - name: forward rule without destination ports
        action: accept
        sources:
          - zone: lan
            subnets: true
            sets:
              - external-hosts-example
              - wan_ip
        destinations:
          - zone: wan
            sets:
              - wan_ip
          - zone: wan
            sets:
              - external-hosts-example
          - zone: lab
            subnets: true

  roles:
    - role: nftables
