---
- name: Stop and disable conflicting service {{ item }}
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  when:
    - nftables_conflicting_services is defined
    - ansible_facts.services[item ~ '.service'] is defined
  loop: "{{ nftables_conflicting_services }}"
