---
# handlers file for ansible-nftables
- name: Restart nftables service
  ansible.builtin.service:
    name: nftables
    enabled: true
    state: restarted
  become: true

- name: Refresh nftables urls
  command: /usr/local/bin/nftables_url_script.sh no_reload
  become: true

- name: Systemctl daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
